### PR TITLE
Marginal Probabilities

### PR DESCRIPTION
**Pull request by JeppeHallgren**
This computes the marginal probabilities of the given emissions (the probability of seeing a tag T and at position P in the sequence).

Tests and linters pass.

### CODE REVIEW

**Comment by JeppeHallgren** [comment]
Hey @kmkurn , any chance you have time to look at this PR?

**Comment by kmkurn** [comment]
Hi @JeppeHallgren. Really sorry for the (very) late response. I've been busy with work and other stuff.

I think I can review your changes this week, but could you please explain a bit what `alpha` and `beta` compute? Thanks!

**Comment by keishinkickback** [comment]
Hi @JeppeHallgren  and @kmkurn,
How long do you think it takes to merge this PR? I want marginal probabilities as well, and I would really appreciate it if you guys could merge this soon. As to `alpha` and `beta`, I think those notations are from [Forward-backward algorithm](https://ivi.fnwi.uva.nl/cv/events/enterface10/pdf/lecture3_crfs.pdf#page=18).

**Comment by kmkurn** [comment]
Hi @keishinkickback. Can't say for sure. The codebase has been refactored quite heavily recently, and now any PR should generally be merged to `develop` instead of `master` branch. I can probably implement this myself if required, but I can't promise when. The best thing you can do is to implement this yourself based on this code, sorry.

**Comment by keishinkickback** [comment]
@kmkurn I see. Yup, the code looks so much cleaner than the last time I checked! Thanks!

**Comment by JeppeHallgren** [comment]
@keishinkickback I will have some time to look at this in late February, but if you need this merged before feel free to work on top of my PR

**Comment by kmkurn** [comment]
Hi @JeppeHallgren. The PR should be made to `master` branch, not `develop`. It was an old branch which I probably should've deleted to avoid the confusion. Sorry.

**Comment by JeppeHallgren** [comment]
Closing this in favour of https://github.com/kmkurn/pytorch-crf/pull/21

**Comment by robinsongh381** [comment]
Would it be possible to get the probability for the optimal sequence with the marginal probability ?

I am looking for a way to get the probability for the optimal sequence

**Comment by Dhanachandra** [comment]
Hi @JeppeHallgren, 
The index of the highest marginal probability for the last timestamp is not matched with the last element in the best_tags_list. 

```
num_tags = 4  # number of tags is 5
model = CRF(num_tags)

seq_length = 3  # maximum sequence length in a batch
batch_size = 2  # number of samples in the batch
emissions = torch.randn(seq_length, batch_size, num_tags)
mask = torch.tensor([[1, 1], [1, 1], [1, 1]])
#print('After emissions:', emissions)
mg_prob = model.compute_marginal_probabilities(emissions, mask)
out_seqs =  model.decode(emissions, mask)

mg_p = F.softmax(mg_prob.view(batch_size, seq_length, -1), dim=-1)

print("MG prob: ", mg_prob.view(batch_size, seq_length, -1))
print('Out seqs: ', out_seqs)
```
Output: 
MG prob:  tensor([[[0.2094, 0.1138, 0.5104, 0.1664],
         [0.2233, 0.4624, 0.1504, 0.1639],
         [0.0739, 0.3609, 0.3825, 0.1828]],

        [[0.2059, 0.1785, 0.4305, 0.1850],
         [0.0153, 0.0553, 0.1094, 0.8200],
         [0.0299, 0.0442, **0.8378**, 0.0882]]], grad_fn=<ViewBackward>)
Out seqs:  [[2, 2, 3], [1, 2, **2**]]

**Pull request closed without merging**
